import type { PortfolioImage } from "@/types";
import { PORTFOLIO_CATEGORIES } from "@/types";

/**
 * Central photography catalog for xFinta / Murtada AlHajari.
 * 
 * Every `src` below already points at its final expected file under
 * public/media/<category-folder>/ — see the README.md in each folder for
 * the exact filename list. Until a real file exists at that path,
 * PlaceholderImage automatically renders a gradient placeholder instead
 * (see src/components/ui/PlaceholderImage.tsx), so the site always looks
 * complete. Drop in a matching file and it goes live — no code changes.
 */
export const portfolioImages: PortfolioImage[] = [
  // ---- Product Photography (public/media/product-photography/) ----
  {
    id: "prod-01",
    slug: "hoodie",
    title: "Hoodie Clothing Photo Shoot",
    description: "Clean flat-lay studio shot for an apparel catalog.",
    category: "Product Photography",
    tags: ["apparel", "flat lay", "studio"],
    orientation: "square",
    src: "/media/product-photography/product-01.jpg",
    alt: "Flat-lay studio product photography of a black hoodie",
  },
  {
    id: "prod-02",
    slug: "reesheh-label-detail",
    title: "Shirt Clothing Photo Shoot",
    description: "Close-up on fabric and branding",
    category: "Product Photography",
    tags: ["apparel", "detail", "macro"],
    orientation: "square",
    src: "/media/product-photography/product-02.jpg",
    alt: "Close-up of a navy t-shirt collar and brand label",
  },
  {
    id: "prod-03",
    slug: "sock-detail",
    title: "Socks Clothing Photo Shoot",
    description: "Macro texture shot highlighting the knit.",
    category: "Product Photography",
    tags: ["apparel", "macro", "texture"],
    orientation: "square",
    src: "/media/product-photography/product-03.jpg",
    alt: "Macro detail shot of no-show socks with a contrast toe",
  },
  {
    id: "prod-04",
    slug: "sock-photo-shoot",
    title: "Socks Clothing Photo Shoot",
    description: "Clean studio product shot on a white background.",
    category: "Product Photography",
    tags: ["apparel", "studio"],
    orientation: "square",
    src: "/media/product-photography/product-04.jpg",
    alt: "Product photography of a pair of grey striped ankle socks",
  },
  {
    id: "prod-05",
    slug: "yamac-iced-mint",
    title: "Yamac Iced Mint",
    description: "High-speed splash photography for a beverage brand.",
    category: "Product Photography",
    tags: ["beverage", "splash", "drink"],
    orientation: "portrait",
    featured: true,
    src: "/media/product-photography/product-05.jpg",
    alt: "Splash photography of a Yamaç iced mint and lemon drink",
  },
  {
    id: "prod-06",
    slug: "cukur-blueberry-mint",
    title: "Çukur Blueberry Mint",
    description: "High-speed splash photography for a beverage brand.",
    category: "Product Photography",
    tags: ["beverage", "splash", "drink"],
    orientation: "portrait",
    src: "/media/product-photography/product-06.jpg",
    alt: "Splash photography of a Çukur blueberry mint drink with falling berries",
  },
  {
    id: "prod-07",
    slug: "boba-bay-duo",
    title: "Boba Bay Photo Shoot",
    description: "Boba Bay drinks photo shoot",
    category: "Product Photography",
    tags: ["beverage", "bubble tea"],
    orientation: "landscape",
    featured: true,
    src: "/media/product-photography/product-07.jpg",
    alt: "Two Boba Bay bubble tea drinks styled on wooden coasters",
  },
  {
    id: "prod-08",
    slug: "boba-bay-thai-tea",
    title: "Boba Bay Tea",
    description: "Boba Bay drink photo shoot.",
    category: "Product Photography",
    tags: ["beverage", "bubble tea"],
    orientation: "portrait",
    src: "/media/product-photography/product-08.jpg",
    alt: "Boba Bay Thai tea bubble tea drink with a scoop of tapioca pearls",
  },
  {
    id: "prod-09",
    slug: "coconut-soft-serve",
    title: "Icecream Photo Shoot",
    description: "Action shot of coconut flakes finishing a soft-serve cone.",
    category: "Product Photography",
    tags: ["dessert", "food", "action"],
    orientation: "portrait",
    src: "/media/product-photography/product-09.jpg",
    alt: "Hands sprinkling coconut flakes onto soft-serve ice cream in a coconut shell",
  },
  {
    id: "prod-10",
    slug: "boba-bay-brown-sugar",
    title: "Boba Bay drink photo shoot",
    description: "Studio product shot styled against a muted green backdrop.",
    category: "Product Photography",
    tags: ["beverage", "bubble tea"],
    orientation: "portrait",
    src: "/media/product-photography/product-10.jpg",
    alt: "Boba Bay brown sugar milk tea styled against a green background",
  },
  {
    id: "prod-11",
    slug: "boba-bay-coffee-campaign",
    title: "Boba Bay Coffee Campaign",
    description: "Composite campaign visual with splash effects and coffee beans.",
    category: "Product Photography",
    tags: ["beverage", "advertising", "campaign"],
    orientation: "portrait",
    src: "/media/product-photography/product-11.jpg",
    alt: "Advertising campaign visual for a Boba Bay coffee bubble tea drink",
  },
  {
    id: "prod-12",
    slug: "boba-bay-red-berry-campaign",
    title: "Boba Bay Tea Campaign",
    description: "Composite campaign visual for a seasonal iced tea.",
    category: "Product Photography",
    tags: ["beverage", "advertising", "campaign"],
    orientation: "portrait",
    src: "/media/product-photography/product-12.jpg",
    alt: "Advertising campaign visual for a Boba Bay red berry iced tea",
  },

  // ---- Wedding Photography (public/media/wedding-photography/) ----
  {
    id: "wed-01",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["groom", "portrait", "studio"],
    orientation: "portrait",
    featured: true,
    src: "/media/wedding-photography/wedding-01.jpg",
    alt: "Portrait of a groom in traditional Gulf wedding attire",
  },
  {
    id: "wed-02",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["family", "portrait"],
    orientation: "portrait",
    src: "/media/wedding-photography/wedding-02.jpg",
    alt: "Portrait of an elder family member in traditional wedding attire",
  },
  {
    id: "wed-03",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["groom", "candid"],
    orientation: "portrait",
    src: "/media/wedding-photography/wedding-03.jpg",
    alt: "Groom glimpsed through curtains adjusting his headwear",
  },
  {
    id: "wed-04",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["groom", "candid", "guests"],
    orientation: "landscape",
    src: "/media/wedding-photography/wedding-04.jpg",
    alt: "Groom smiling candidly while surrounded by guests",
  },
  {
    id: "wed-05",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["groom", "candid", "guests"],
    orientation: "landscape",
    src: "/media/wedding-photography/wedding-05.jpg",
    alt: "Groom walking through a crowd of guests wearing a floral garland",
  },
  {
    id: "wed-06",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["celebration", "candid", "night"],
    orientation: "landscape",
    featured: true,
    src: "/media/wedding-photography/wedding-06.jpg",
    alt: "Groom celebrating with a crowd of friends and family at night",
  },
  {
    id: "wed-07",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["portrait", "garland"],
    orientation: "portrait",
    src: "/media/wedding-photography/wedding-07.jpg",
    alt: "Portrait of a man wearing a red and yellow floral wedding garland",
  },
  {
    id: "wed-08",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["groom", "portrait", "garland"],
    orientation: "portrait",
    src: "/media/wedding-photography/wedding-08.jpg",
    alt: "Groom seated wearing a red and white rose garland",
  },
  {
    id: "wed-09",
    slug: "",
    title: "",
    description: "",
    category: "Wedding Photography",
    tags: ["guests", "candid"],
    orientation: "portrait",
    src: "/media/wedding-photography/wedding-09.jpg",
    alt: "Two guests greeting each other warmly, one wearing a floral garland",
  },

  // ---- Architecture Photography (public/media/architecture-photography/) ----
  // {
  //   id: "arch-01",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "minaret", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-01.jpg",
  //   alt: "Mosque minaret framed by folded courtyard umbrellas",
  // },
  // {
  //   id: "arch-02",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "arches", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-02.jpg",
  //   alt: "Low-angle view of striped mosque courtyard arches",
  // },
  // {
  //   id: "arch-03",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "arches", "symmetry"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/architecture-photography/architecture-03.jpg",
  //   alt: "Repeating mosque archways receding into the interior",
  // },
  // {
  //   id: "arch-04",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "detail", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-04.jpg",
  //   alt: "Ornate door frame with a minaret visible against the sky",
  // },
  // {
  //   id: "arch-05",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["construction", "urban"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-05.jpg",
  //   alt: "Construction crane towering over a scaffolded building",
  // },
  // {
  //   id: "arch-06",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["minaret", "golden hour"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-06.jpg",
  //   alt: "Mosque minaret at golden hour with mountains in the background",
  // },
  // {
  //   id: "arch-07",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["minaret", "dusk"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/architecture-photography/architecture-07.jpg",
  //   alt: "Two mosque minarets silhouetted against a dusk sky",
  // },
  // {
  //   id: "arch-08",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "detail", "calligraphy"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-08.jpg",
  //   alt: "Carved stone latticework and calligraphy above a mosque gate",
  // },
  // {
  //   id: "arch-09",
  //   slug: "mosque-at-night",
  //   title: "Mosque at Night",
  //   description: "Warm uplighting brings the facade to life after dark.",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "night"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-09.jpg",
  //   alt: "Illuminated mosque facade and minaret at night",
  // },
  // {
  //   id: "arch-10",
  //   slug: "water-tower-at-night",
  //   title: "Water Tower at Night",
  //   description: "A landmark water tower glows pink and green above the palms.",
  //   category: "Architecture Photography",
  //   tags: ["landmark", "night", "lighting"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/architecture-photography/architecture-10.jpg",
  //   alt: "Illuminated water tower landmark glowing pink and green at night",
  // },
  // {
  //   id: "arch-11",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["minaret", "sunset"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-11.jpg",
  //   alt: "Mosque minaret and crenellated wall at sunset",
  // },
  // {
  //   id: "arch-12",
  //   slug: "the-dome-ceiling",
  //   title: "The Dome Ceiling",
  //   description: "A geometric star pattern radiates across an ornate dome.",
  //   category: "Architecture Photography",
  //   tags: ["mosque", "dome", "interior"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/architecture-photography/architecture-12.jpg",
  //   alt: "Ornate geometric star pattern on a mosque dome ceiling",
  // },
  // {
  //   id: "arch-13",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["interior", "lighting", "detail"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-13.jpg",
  //   alt: "Warm filament bulb hanging beneath trailing indoor greenery",
  // },
  // {
  //   id: "arch-14",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Architecture Photography",
  //   tags: ["airport", "facade", "commercial"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-14.jpg",
  //   alt: "Exterior facade of King Fahd International Airport terminal",
  // },
  // {
  //   id: "arch-15",
  //   slug: "covered-walkway",
  //   title: "Covered Walkway",
  //   description: "A shaded pergola walkway leads toward a garden doorway.",
  //   category: "Architecture Photography",
  //   tags: ["walkway", "garden", "exterior"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-15.jpg",
  //   alt: "Shaded pergola walkway leading to a garden entrance",
  // },
  // {
  //   id: "arch-16",
  //   slug: "spheres-of-light",
  //   title: "Spheres of Light",
  //   description: "A cluster of sparkling pendant lights fills a curved ceiling recess.",
  //   category: "Architecture Photography",
  //   tags: ["interior", "lighting", "lobby"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-16.jpg",
  //   alt: "Cluster of spherical pendant lights in a modern ceiling recess",
  // },
  // {
  //   id: "arch-17",
  //   slug: "the-kaaba",
  //   title: "The Kaaba",
  //   description: "Pilgrims gather beneath the Kaaba, surrounded by ongoing expansion works.",
  //   category: "Architecture Photography",
  //   tags: ["makkah", "heritage", "pilgrimage"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/architecture-photography/architecture-17.jpg",
  //   alt: "The Kaaba in Makkah surrounded by pilgrims",
  // },
  // {
  //   id: "arch-18",
  //   slug: "the-clock-tower",
  //   title: "The Clock Tower",
  //   description: "The Makkah Royal Clock Tower rises above a historic bridge.",
  //   category: "Architecture Photography",
  //   tags: ["makkah", "landmark"],
  //   orientation: "portrait",
  //   src: "/media/architecture-photography/architecture-18.jpg",
  //   alt: "Makkah Royal Clock Tower viewed from below with an ornate bridge in the foreground",
  // },

  // // ---- Random (public/media/random/) ----
  // // A catch-all for personal work, street shots, travel, and anything else
  // // that doesn't fit neatly into the categories above.
  // {
  //   id: "rand-01",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["portrait", "sports", "color pop"],
  //   orientation: "landscape",
  //   src: "/media/random/random-01.jpg",
  //   alt: "Boy in a red jersey standing out in color against a black-and-white background",
  // },
  // {
  //   id: "rand-02",
  //   slug: "",
  //   title: "T",
  //   description: "",
  //   category: "Random",
  //   tags: ["nature", "birds", "wildlife"],
  //   orientation: "landscape",
  //   src: "/media/random/random-02.jpg",
  //   alt: "Bird taking flight off shallow water near a rocky shoreline",
  // },
  // {
  //   id: "rand-03",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["nature", "birds", "wildlife"],
  //   orientation: "landscape",
  //   src: "/media/random/random-03.jpg",
  //   alt: "Bird perched among palm fronds against a blue sky",
  // },
  // {
  //   id: "rand-04",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["nature", "birds", "sky"],
  //   orientation: "landscape",
  //   src: "/media/random/random-04.jpg",
  //   alt: "Two seagulls flying through a cloudy sky",
  // },
  // {
  //   id: "rand-05",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["nature", "birds", "silhouette"],
  //   orientation: "landscape",
  //   src: "/media/random/random-05.jpg",
  //   alt: "Silhouette of a crow in flight against cloudy skies",
  // },
  // {
  //   id: "rand-06",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["food", "macro", "still life"],
  //   orientation: "landscape",
  //   src: "/media/random/random-06.jpg",
  //   alt: "Macro still life of a sliced pomegranate with peppers and mint",
  // },
  // {
  //   id: "rand-07",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["lifestyle", "books", "cozy"],
  //   orientation: "landscape",
  //   src: "/media/random/random-07.jpg",
  //   alt: "Hand holding a travel memoir book in a cozy, candlelit reading nook",
  // },
  // {
  //   id: "rand-08",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["behind the scenes", "video editing"],
  //   orientation: "landscape",
  //   src: "/media/random/random-08.jpg",
  //   alt: "Video editing timeline and color grading panel on a monitor",
  // },
  // {
  //   id: "rand-09",
  //   slug: "moon-behind-clouds",
  //   title: "Moon Behind Clouds",
  //   description: "A full moon breaking through drifting night clouds.",
  //   category: "Random",
  //   tags: ["night", "moon", "sky"],
  //   orientation: "square",
  //   src: "/media/random/random-09.jpg",
  //   alt: "Full moon glowing behind night clouds",
  // },
  // {
  //   id: "rand-10",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["creative", "composite", "moon"],
  //   orientation: "square",
  //   src: "/media/random/random-10.jpg",
  //   alt: "Creative composite image of a crescent moon and a glowing lightbulb",
  // },
  // {
  //   id: "rand-11",
  //   slug: "jump-start",
  //   title: "Jump Start",
  //   description: "Sparks fly during a roadside car battery jump-start.",
  //   category: "Random",
  //   tags: ["automotive", "sparks", "behind the scenes"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/random/random-11.jpg",
  //   alt: "Mechanic jump-starting a car battery with sparks flying",
  // },
  // {
  //   id: "rand-12",
  //   slug: "facing-the-sea",
  //   title: "Facing the Sea",
  //   description: "A quiet moment on the rocks, facing the water.",
  //   category: "Random",
  //   tags: ["travel", "portrait", "sea"],
  //   orientation: "portrait",
  //   src: "/media/random/random-12.jpg",
  //   alt: "Person standing on rocks facing the sea with arms outstretched",
  // },
  // {
  //   id: "rand-13",
  //   slug: "stray",
  //   title: "Stray",
  //   description: "A stray kitten finds a quiet corner to rest.",
  //   category: "Random",
  //   tags: ["animals", "street"],
  //   orientation: "portrait",
  //   src: "/media/random/random-13.jpg",
  //   alt: "Stray kitten resting in a tiled corner",
  // },
  // {
  //   id: "rand-14",
  //   slug: "morning-ritual",
  //   title: "Morning Ritual",
  //   description: "Coffee, a good book, and a slow start to the day.",
  //   category: "Random",
  //   tags: ["lifestyle", "coffee", "black and white"],
  //   orientation: "portrait",
  //   src: "/media/random/random-14.jpg",
  //   alt: "Black and white top-down photo of a hand holding coffee beside an open book",
  // },
  // {
  //   id: "rand-15",
  //   slug: "unfinished",
  //   title: "Unfinished",
  //   description: "A stairwell inside an unfinished concrete building.",
  //   category: "Random",
  //   tags: ["urban", "architecture", "moody"],
  //   orientation: "portrait",
  //   src: "/media/random/random-15.jpg",
  //   alt: "Dark stairwell inside an unfinished concrete building",
  // },
  // {
  //   id: "rand-16",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-16.jpg",
  //   alt: "Low-angle view of mosque courtyard arches in Madinah",
  // },
  // {
  //   id: "rand-17",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-17.jpg",
  //   alt: "Ornate mosque door frame with a minaret visible against the sky",
  // },
  // {
  //   id: "rand-18",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-18.jpg",
  //   alt: "Repeating mosque archways receding into the distance",
  // },
  // {
  //   id: "rand-19",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-19.jpg",
  //   alt: "Geometric window grid inside a mosque, backlit with soft light",
  // },
  // {
  //   id: "rand-20",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-20.jpg",
  //   alt: "Ornate numbered mosque entrance gate with gold detailing",
  // },
  // {
  //   id: "rand-21",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/random/random-21.jpg",
  //   alt: "Ornate golden mosque door with Arabic calligraphy detailing",
  // },
  // {
  //   id: "rand-22",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["construction", "urban"],
  //   orientation: "portrait",
  //   src: "/media/random/random-22.jpg",
  //   alt: "Construction crane towering over a scaffolded building",
  // },
  // {
  //   id: "rand-23",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah"],
  //   orientation: "portrait",
  //   src: "/media/random/random-23.jpg",
  //   alt: "Green-domed minaret framed by palm tree fronds",
  // },
  // {
  //   id: "rand-24",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "madinah", "video"],
  //   orientation: "portrait",
  //   featured: true,
  //   src: "/media/random/random-24.jpg",
  //   alt: "Title card reading Madinah Montage over the Prophet's Mosque green dome",
  // },
  // {
  //   id: "rand-25",
  //   slug: "",
  //   title: "",
  //   description: "",
  //   category: "Random",
  //   tags: ["travel", "mosque", "madinah", "aerial"],
  //   orientation: "landscape",
  //   src: "/media/random/random-25.jpg",
  //   alt: "Elevated wide view of the Prophet's Mosque courtyard in Madinah",
  // },
];

export const portfolioCategories = PORTFOLIO_CATEGORIES;
